language: php
php:
  # aliased to 5.2.17
  - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  - 5.4
script: make test
notifications:
  email: "tech@tempo-db.com"
